### ISSUE TITLE
Continue to execute task if any sequence task in between gets failed

### ISSUE THREAD

**Issue by janardanb** [OverZealous/run-sequence#103]
i want to continue to execute task if any sequence task in between gets failed..  i am not able to find the solution :(

t1 t2 t3 t4

i am calling this in t5
t5(t1 t2 t3 t4)

and it t3 fails t4 doesn't execute it simply stop the execution but i want to execute t4 inspite of any task which is failed..  Thanks

**Comment by OverZealous** [comment]
Run-sequence doesn't support this because gulp doesn't support this. If a task fails—any task—gulp quits, and therefore run-sequence quits.

If you want to continue after a task fails, you need to catch that error and prevent it from propagating. Since every stream is a little different, I can't help you with that.

The other alternative is to not return anything from t3 if nothing depends on it's completion, or wrap it in something to ensure you return successfully whether it completes or not.
