### ISSUE TITLE
del() and the callback

### ISSUE THREAD

**Issue by tristanlins** [OverZealous/run-sequence#54]
The readme says:

```js
gulp.task('build-clean', function(callback) {
    del([BUILD_DIRECTORY], callback);
//                         ^^^^^^^^ 
//   This is the key here, to make sure tasks run asynchronously! 
});
```

But this is wrong now, the documentation of [del](https://www.npmjs.com/package/del) says:

```js
del(['tmp/*.js', '!tmp/unicorn.js']).then(function (paths) {
    console.log('Deleted files/folders:\n', paths.join('\n'));
});
```

I must change my tasks like this, to get it working:

```js
gulp.task('build-clean', function(callback) {
    del([BUILD_DIRECTORY]).then(function(){
        callback();
    });
});
```

**Comment by OverZealous** [comment]
I don't personally care, someone else made the change to `del`, it's just an example showing async callbacks.

Feel free to make a PR with the updated solution.  However, please note there is no reason to use the callback when returning a promise—gulp will handle promises correctly, like so:

```js
gulp.task('build-clean', function() {
    return del([BUILD_DIRECTORY]);
});
```

Notice you can't have the `callback` argument in the task method, otherwise the task will never end.

**Comment by viveleroi** [comment]
This tripped me up as well - thanks for reporting it/answering it. I couldn't figure out why my sequences were no longer running - the change to `del` was it.
