### ISSUE TITLE
feature request: pass parameter to tasks

### ISSUE THREAD

**Issue by lzl124631x** [OverZealous/run-sequence#68]
With the help of `yargs`, one can call `gulp taskName --parameterName argumentValue`. However, `run-sequence` doesn't seem to support this. Add it?

**Comment by OverZealous** [comment]
What does this have to do with `run-sequence`?

**Comment by lzl124631x** [comment]
An example case as follows.

```
gulp.task('staging', function(cb) {
   // retrieve config for staging
   runSequence('build', 'postprocess --config stagingConfig', cb);
});
gulp.task('production', function(cb) {
   // retrieve config for production
   runSequence('build', 'postprocess --config productionConfig', cb);
});
```

**Comment by OverZealous** [comment]
The `yargs` commands are on the command line.  Run-sequence just runs the tasks within gulp.  You can't call `gulp.start('task param')`, either.

Sorry, this just doesn't make any sense.

**Comment by lzl124631x** [comment]
Then can you suggest me a elegant way to pass parameter to tasks ran by `run-sequence`? Global variable?

**Comment by OverZealous** [comment]
Again, what does this have to do with `run-sequence`? If you want command-line parameters in your task, just use them the same way.  All run-sequence does is start one or more tasks, wait for it them complete, then start the next set.

Everything else is normal gulp.

**Comment by lzl124631x** [comment]
Ok, thx:)

**Comment by napalm684** [comment]
I would like to re-iterate this as a feature request.  Yes it doesn't directly relate to your tool but your package is an orchestrator for gulp task executions across multiple files.  Currently if I pass a task name to run-sequence with a parameter value it will not find a task by that name (which is correct because it's an argument not a part of the task name).  Gulp itself handles this fine ie: gulp taskname --argument (executing taskname passing the "argument").  I would like to be able to do something akin to the following:

```
gulp.task('build-libraries', [
    'compress-libraries --en',
    'compress-libraries --de'
]);
```

This saves me from writing the same gulp task twice.  Hope this helps lend some clarity to the request @lzl124631x was trying to express and why it would be a valid feature.

**Comment by OverZealous** [comment]
Tasks don't take arguments, your point is invalid.  The comments above stand. 

If you want to run a task in different ways, then wrap it in a task that calls a function.  Or configure a loop.  The problem you have is the way you've set up your build process.

Gulp doesn't process those arguments either. There's literally no way for me to solve this.  All `run-sequence` does is tell gulp to run the tasks requested.

**Comment by napalm684** [comment]
I disagree this is not an invalid point.  Tasks can take arguments with additional help:

See this [Stackoverflow post](http://stackoverflow.com/questions/28538918/pass-parameter-to-gulp-task) for details.

So while yes officially they do not support arguments yet, they can through other means.  Can you riddle me this since you obviously know a lot about gulp, in the event of calling gulp task --argument it does work, does gulp purely ignore this?  IE: can you just pass the argument from run-sequence's array as is to a gulp command, so gulp <the argument>.  I am guessing that is not how the library works without me digging in though.  Sure there are other ways this would have been the cleanest for me.

**Comment by OverZealous** [comment]
You are simply wrong.  Tasks do _not_ take arguments.  There is no "yet". Programs can accept arguments on the command line, that is all that SO post is referencing.  Tasks within gulp do not take arguments.

The program takes arguments, and your code and/or tasks can read those arguments.  The arguments are handled when the program is started.  The tasks themselves only accept a single argument for processing asynchronous code.

> I am guessing that is not how the library works without me digging in though

`run-sequence` is [just barely over 100 lines of code](https://github.com/OverZealous/run-sequence/blob/master/index.js).  Understanding how it works would only take a couple of minutes. Not only that, the core functionality is explained near the top of the README.

If you haven't taken the time to understand how *either* library works, then don't say it's not an invalid point. It's completely invalid.

**Comment by napalm684** [comment]
Ok first off rudeness is not necessary.  Second your point that my point is invalid simply isn't the case.  From a functionality standpoint it is possible to have "arguments" notice the double quotes as I am fully aware they aren't true arguments.  There wasn't a need to be so literal about it.  I did take the time to understand the argument functionality for what I needed to.  Admittedly your 100 lines of code I should have looked at.  

Now for some honest feedback, no criticism.  Part of open source is being a good community member.  You come off as incredibly hostile which can be a large deterrent for new developers to get involved.  Just some food for thought.

**Comment by OverZealous** [comment]
I'm only "hostile" because I already explained this above, before your comment. And I don't think my initial comment was hostile, anyway.

You responded with "Tasks can take arguments with additional help:", which, again, is wrong. You didn't even take the time to understand my response, or the previous comments above.  I said "Gulp doesn't process those arguments" and I even provided an example earlier, "You can't call `gulp.start('task param')`"

-----

Some feedback for your feedback:

Creating an OSS library effectively means answering the same questions over and over again. From people who can't be bothered to take the time to understand the library (even a simple one), then want features that aren't related.

Being involved in OSS means doing more on _both_ sides of the coin. You shouldn't just pop in to a library and drop a comment or make a request. You need to take the time to dig into the source (it's open for a reason), and read the documentation. You should understand how the code works well enough—the concern you have is not even with this library, as I mentioned previously, as `gulp` itself doesn't support that feature.

Asking for features without understanding the library just makes more work for someone who is already offering their time for free.

**Comment by kapooostin** [comment]
@napalm684 You can either call your gulp task containing `run-sequence` _with a parameter_:`gulp your-task --parameter-for-subtask=something` or create preconfigured variants of your subtask.

**Comment by kushdilip** [comment]
@lzl124631x Whatever arguments you pass to parent tasks(`staging` or `production`) will be available to all the subtasks which you call using `run-sequence`. You have to use yargs to access them.

Let's say you execute command `gulp staging  --something`

then inside child task `postprocess` you can access it directly.


`$ gulp staging  --something`

```
var yargs  = require('yargs').argv,

gulp.task('staging', function(cb) {
   // retrieve config for staging
   runSequence('build', 'postprocess', cb);
});

gulp.task('postprocess', function () {
   var isSomething = (yargs.something === undefined) ? false : true;
   // rest of the code
}

**Comment by lzl124631x** [comment]
@kushdilip Thanks.

1. I was lazy to type the configs into command line. Just want `gulp staging`, not `gulp staging --bla bla`
2. there are tens of entries of configs which I saved into config files and were loaded at the run-time.
3. I don't want to use global variable for configs.

If there is no way to pass in parameter, I can compromise the 3rd point -- use custom global variable or just attach config key-value-pairs onto `yargs`.

```
var config; // <-- global variable

function retrieveConfig(configFileName) {/*....*/}

gulp.task('staging', function(cb) {
   config = retrieveConfig('stagingConfig.xml');
   runSequence('build', 'postprocess', cb);
});
```

or

```
var argv = require('yargs').argv;
function retrieveConfig(configFileName) {
   argv.configA = /* ... */;
   argv.configB = /* ... */;
}
```
