### ISSUE TITLE
It seems like not suitable for arrow function in es6?

### ISSUE THREAD

**Issue by paraofheaven** [OverZealous/run-sequence#95]
I want to use a gulp task to run the sequence,but when I use arrow function to contain , like this:
```
gulp.task('watch', () => {
  const scripts = _.union(paths.client.scripts, []);
  plugins.watch(scripts, ()=> {
    runSequence(['eslint']);
  })
});
```
it errors,and throw msg like: 
*"Task [object object] is not a valid task string."*
I know it use arguments as param,that cause the error,however should it be solved？or something improved.
sorry for the expression,I am chinalish.:-D
thanks.

**Comment by OverZealous** [comment]
Are you saying it works when you switch to traditional anonymous function expressions?

This makes no sense, since the call to `runSequence` has nothing to do with the surrounding context. The error you are seeing says you are trying to pass a non-string argument into `runSequence`.

The example you have above doesn't make sense, anyway, because you are wrapping the single task in an array.

Please try to reduce the issue to a minimal test case which shows the issue, because honestly, the code you have above won't cause the error your are saying you see.

**Comment by paraofheaven** [comment]
oops,I have find my mistake,as before my code like this:
```
gulp.task('watch', () => {
  const scripts = _.union(paths.client.scripts, []);
  plugins.watch(scripts, (callback) =>
    runSequence(['eslint],callback)
  )
});
```
now I realize the second param **callback** in pugins.watch is not a function ,sorry for that .next time next issue I will add minimal case.

**Comment by OverZealous** [comment]
Great! Glad you were able to solve it!
